# .slather.yml
ci_service: travis_ci
coverage_service: coveralls
xcodeproj: GroceryList.xcodeproj
# workspace: GroceryList.xcworkspace
scheme: GroceryList
# source_directory: ShowMeTheGames/
ignore: 
  -  GroceryList/AppDelegate.swift